


const fs = require('fs');
const path = require('path');
const https = require('https');

const baseUrl = "https://intelreap.com";
const pagesFile = "./data/pages.json";
const registryFile = "./js/registry.js";
const sitemapFile = "./sitemap.xml";
const indexNowKey = "833b2f9ffb7d41ba9ed2ef3ea392d9c1"; // your exact key

// Create folders if missing
if (!fs.existsSync("./data")) fs.mkdirSync("./data");
if (!fs.existsSync("./js")) fs.mkdirSync("./js");

// 1. Find all .html files in root
const allFiles = fs.readdirSync(".")
  .filter(f => f.endsWith(".html"))
  .map(f => `./${f}`);

// 2. Load existing pages or start fresh
let existingPages = [];
if (fs.existsSync(pagesFile)) {
  existingPages = JSON.parse(fs.readFileSync(pagesFile, "utf8"));
}

// 3. Build updated pages list
const newPages = [];
allFiles.forEach(filePath => {
  const filename = path.basename(filePath);
  const slug = filename === "index.html" ? "" : filename.replace(".html", "");

  // Keep your custom metadata if page already exists
  let page = existingPages.find(p => p.slug === slug);
  if (!page) {
    page = {
      slug: slug,
      title: (slug || "home").split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(" "),
      type: "info",
      priority: 0.5
    };
  }

  // Real last-modified date for SEO
  const stats = fs.statSync(filePath);
  page.lastmod = stats.mtime.toISOString().split("T")[0];

  newPages.push(page);
});

// 4. Save pages.json
fs.writeFileSync(pagesFile, JSON.stringify(newPages, null, 2));
console.log("✅ pages.json updated with detected HTML pages");

// 5. Rebuild registry.js
const registryContent = `// AUTO-GENERATED by generate-all.js
const siteRegistry = ${JSON.stringify(newPages, null, 2)};

if (typeof window !== "undefined") { window.siteRegistry = siteRegistry; } else { module.exports = siteRegistry; }`;
fs.writeFileSync(registryFile, registryContent);
console.log("✅ registry.js updated");

// 6. Rebuild sitemap.xml with real dates
let xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`;
newPages.forEach(page => {
  const urlSlug = page.slug === "" ? "" : "/" + page.slug;
  const changefreq = page.type === "tool" ? "daily" : (page.type === "guide" ? "weekly" : "monthly");
  const lastmod = page.lastmod || new Date().toISOString().split("T")[0];

  xml += `
  <url>
    <loc>${baseUrl}${urlSlug}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>`;
});
xml += "\n</urlset>";
fs.writeFileSync(sitemapFile, xml);
console.log("✅ sitemap.xml updated");

// 7. Ping Google
https.get(`https://www.google.com/ping?sitemap=${encodeURIComponent(baseUrl + "/sitemap.xml")}`, () => {
  console.log("✅ Google pinged");
});

// 8. Ping IndexNow
const urls = newPages.map(p => baseUrl + (p.slug === "" ? "" : "/" + p.slug));
const data = JSON.stringify({ host: "intelreap.com", key: indexNowKey, urlList: urls });
const options = {
  hostname: "api.indexnow.org",
  path: "/indexnow",
  method: "POST",
  headers: { "Content-Type": "application/json", "Content-Length": data.length }
};
const req = https.request(options, () => console.log("✅ IndexNow pinged"));
req.write(data);
req.end();

console.log("\n🎉 ALL DONE! New HTML pages auto-detected. Files updated & search engines pinged.");
